---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyrescom-data-pvc
  namespace: {? {.Values.namespace}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {? {.Values.services.pyrescom.ressources.storageClassName}}
  resources:
    requests:
      storage: 10Gi
