{{- $service := .Values.services.pyrescom }}
---
apiVersion: v1
kind: Service
metadata:
  name: pyrescom
  namespace: {{ .Values.namespace }}
  labels:
    app: pyrescom
spec:
  type: {{ $service.service.type }}
  selector:
    app: pyrescom
  ports:
    - name: TnView
      protocol: TCP
      port: {{ .Values.configmap.ternet.ServicePort }}
      targetPort: {{ .Values.configmap.ternet.ServicePort }}
    - name: Config
      protocol: TCP
      port: {{ .Values.configmap.ternet.CfgSrvPort }}
      targetPort: {{ .Values.configmap.ternet.CfgSrvPort }}
    - name: https
      protocol: TCP
      port: {{ .Values.configmap.ternet.SslPort }}
      targetPort: {{ .Values.configmap.ternet.SslPort }}
