{{- with .Values.services.pyrescom }}
---
apiVersion: v1
kind: Service
metadata:
  name: pyrescom
  namespace: {{ $.Values.namespace }}
  labels:
    app: pyrescom
    app.kubernetes.io/managed-by: Helm
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  type: {{ .service.type }}
  selector:
    app: pyrescom
  ports:
    {{- with $.Values.configmap.ternet }}
    - name: tnview
      protocol: TCP
      port: {{ .ServicePort }}
      targetPort: {{ .ServicePort }}
    - name: config
      protocol: TCP
      port: {{ .CfgSrvPort }}
      targetPort: {{ .CfgSrvPort }}
    - name: https
      protocol: TCP
      port: {{ .SslPort }}
      targetPort: {{ .SslPort }}
    {{ end }}
{{ end }}
