---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: pyrescom
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
spec:
  {{ with .Values.traefik.gateway }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .name }}
      namespace: {{ .namespace }}
      sectionName: {{ .sectionName }}
  {{ end }}
  hostnames:
    - {{ .Values.traefik.tlsroute.url | quote }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: pyrescom
          port: {{ .Values.configmap.ternet.SslPort }}
          weight: 1
