---
apiVersion: v1
kind: Service
metadata:
  name: kpi
  namespace: { { .Values.namespace } }
spec:
  type: { { .Values.services.kpi.service.type } }
  selector:
    app: kpi
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: http
