{{- with .Values.services.mcp }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp
  namespace: {{ $.Values.namespace }}
  labels:
    app: mcp
    app.kubernetes.io/name: mcp
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: mcp
  template:
    metadata:
      labels:
        app: mcp
        app.kubernetes.io/name: mcp
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ $.Values.registry.secretName }}
      containers:
        - name: mcp
          image: "{{ $.Values.registry.server }}/{{ .image }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          ports:
            {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
          env:
            {{- range $secretName, $secretData := $.Values.secret }}
            {{- range $key, $val := $secretData }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
{{- end }}
