---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-gitlab
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: {{ .Chart.Name }}-{{ .Chart.version }}
spec:
  parentRefs:
    - name: {{ .Values.traefik.gateway.name }}
      namespace: {{ .Values.traefik.gateway.namespace }}
      sectionName: {{ .Values.traefik.gateway.sectionName }}
  hostnames:
    - {{ .Values.traefik.httproute.url }}
  rules:
    - backendRefs:
        - name: mcp-gitlab
          namespace: {{ .Values.namespace }}
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /{{ .Values.traefik.httproute.subPath }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
