{{- if .Values.redis.cluster.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  serviceName: redis
  replicas: {{ .Values.redis.cluster.nodes }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/managed-by: Helm
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.image }}:{{ .Values.redis.image.tag }}
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: bus
          resources:
            {{- if .Values.redis.resources.requests.enabled }}
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu }}
              memory: {{ .Values.redis.resources.requests.memory }}
            {{- end }}
            {{- if .Values.redis.resources.limits.enabled }}
            limits:
              cpu: {{ .Values.redis.resources.limits.cpu }}
              memory: {{ .Values.redis.resources.limits.memory }}
            {{- end }}
          {{- if .Values.redis.healthChecks.enabled }}
          livenessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: {{ .Values.redis.healthChecks.livenessProbe.initialDelaySeconds }}
            periodSeconds:       {{ .Values.redis.healthChecks.livenessProbe.periodSeconds }}
            timeoutSeconds:      {{ .Values.redis.healthChecks.livenessProbe.timeoutSeconds }}
            failureThreshold:    {{ .Values.redis.healthChecks.livenessProbe.failureThreshold }}
          readinessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: {{ .Values.redis.healthChecks.readinessProbe.initialDelaySeconds }}
            periodSeconds:       {{ .Values.redis.healthChecks.readinessProbe.periodSeconds }}
            timeoutSeconds:      {{ .Values.redis.healthChecks.readinessProbe.timeoutSeconds }}
            failureThreshold:    {{ .Values.redis.healthChecks.readinessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/redis
            {{- if .Values.redis.persistency.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: redis-config
  {{- if .Values.redis.persistency.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.redis.persistency.accessModes | nindent 10 }}
        storageClassName: {{ .Values.redis.persistency.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.redis.persistency.storage }}
  {{- end }}

{{- else }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.image }}:{{ .Values.redis.image.tag }}
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
              name: client
          resources:
            {{- if .Values.redis.resources.requests.enabled }}
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu }}
              memory: {{ .Values.redis.resources.requests.memory }}
            {{- end }}
            {{- if .Values.redis.resources.limits.enabled }}
            limits:
              cpu: {{ .Values.redis.resources.limits.cpu }}
              memory: {{ .Values.redis.resources.limits.memory }}
            {{- end }}
          {{- if .Values.redis.healthChecks.enabled }}
          livenessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: {{ .Values.redis.healthChecks.livenessProbe.initialDelaySeconds }}
            periodSeconds:       {{ .Values.redis.healthChecks.livenessProbe.periodSeconds }}
            timeoutSeconds:      {{ .Values.redis.healthChecks.livenessProbe.timeoutSeconds }}
            failureThreshold:    {{ .Values.redis.healthChecks.livenessProbe.failureThreshold }}
          readinessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: {{ .Values.redis.healthChecks.readinessProbe.initialDelaySeconds }}
            periodSeconds:       {{ .Values.redis.healthChecks.readinessProbe.periodSeconds }}
            timeoutSeconds:      {{ .Values.redis.healthChecks.readinessProbe.timeoutSeconds }}
            failureThreshold:    {{ .Values.redis.healthChecks.readinessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/redis
            {{- if .Values.redis.persistency.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: redis-config
        {{- if .Values.redis.persistency.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: redis-data
        {{- end }}

{{- if .Values.redis.persistency.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  accessModes:
    {{- toYaml .Values.redis.persistency.accessModes | nindent 4 }}
  storageClassName: {{ .Values.redis.persistency.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.redis.persistency.storage }}
{{- end }}
{{- end }}
