{{ with .Values.traefik }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: mailind
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .gateway.name }}
      namespace: {{ .gateway.namespace }}
      sectionName: smtp
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: mailind
          port: 25
          weight: 1
{{ end }}
