{{- range $secretName, $secretData := .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
