namespace: "mcp-gitlab"

registry:
  server: "staffngoacr.azurecr.io"
  secretName: "acr-pull-secret"
acrSecret:
  name: "acr-pull-secret"
  username: "staffngoacr"
  password: ""

#----------------------------------------------------
traefik:
  gateway:
    name: "traefik-gateway"
    namespace: "traefik"
    sectionName: "websecure"
  httproute:
    url: "mcp.staffngo.com"
    subPath: "gitlab"

#----------------------------------------------------
services:
  mcp:
    image: "mcp.gitlab"
    tag: "18062025.1"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
    ports:
      - port: 3000
        name: http

#----------------------------------------------------
secret:
  mcp-gitlab-sec:
    REMOTE_GITLAB_MCP_GITLAB_TOKEN: ""
    REMOTE_GITLAB_MCP_PUBLIC_KEY: ""
