{{- with .Values.services.aska }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aska
  namespace: {{ $.Values.namespace }}
  labels:
    app: aska
    app.kubernetes.io/managed-by: Helm
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: aska
  template:
    metadata:
      labels:
        app: aska
    spec:
      imagePullSecrets:
        - name: {{ $.Values.registry.secretName }}
      containers:
        - name: aska
          image: "{{ $.Values.registry.server }}/{{ .image }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          ports:
            - name: {{ .ports.name }}
              containerPort: {{ .ports.port }}
              protocol: TCP
          env:
            {{- range $secretName, $secretData := $.Values.secret }}
            {{- range $key, $val := $secretData }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: aska-data
              mountPath: /aska/resources
              subPath: aska/resources
      volumes:
        - name: aska-data
          persistentVolumeClaim:
            claimName: aska-data-pvc

{{- end }}
