---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aska-data-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.services.aska.resources.storageClassName }}
  resources:
    requests:
      storage: 10Gi
