---
apiVersion: v1
kind: Service
metadata:
  name: aska
  namespace: { { .Values.namespace } }
spec:
  type: { { .Values.services.aska.service.type } }
  selector:
    app: aska
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
