apiVersion: v2
name: pyrescom
description: Déploiement du service Pyrescom
type: application
version: 1.0.0
appVersion: "2026"
icon: https://www.lafrenchfab.fr/storage/sites/2/2024/01/PYRESCOM-300x186.png
