apiVersion: v1
kind: Secret
data:
  API_BASE_URL: {{ printf "%s" .Values.common.secretValues.API_BASE_URL | b64enc }}
  ASPNETCORE_ENVIRONMENT: {{ printf "%s" .Values.environment | b64enc }}
  ASPNETCORE_HTTP_PORTS: {{ printf "%s" .Values.defaults.service.port | b64enc }}
  AZURE_SERVICEBUS_CONNECTION_STRING: {{ printf "%s" .Values.common.secretValues.AZURE_SERVICEBUS_CONNECTION_STRING | b64enc }}
  AZURE_STORAGE_CONNECTION_STRING: {{ printf "%s" .Values.common.secretValues.AZURE_STORAGE_CONNECTION_STRING | b64enc }}
  CLIENT_IDENTITY_URL: {{ printf "%s/identity/#/" .Values.common.secretValues.API_BASE_URL | b64enc }}
  DIGIDOC_URL: {{ printf "http://vault.%s.svc.cluster.local" .Values.namespace | b64enc }}
  EXTERNAL_URL: {{ printf "http://external.%s.svc.cluster.local" .Values.namespace | b64enc }}
  IDENTITY_URL: {{ printf "http://identity.%s.svc.cluster.local" .Values.namespace | b64enc }}
  LABORREGISTER_URL: {{ printf "http://laborregister.%s.svc.cluster.local" .Values.namespace | b64enc }}
  MONITORING_URL: {{ printf "http://monitoring.%s.svc.cluster.local" .Values.namespace | b64enc }}
  NOTIFICATION_URL: {{ printf "http://notification.%s.svc.cluster.local" .Values.namespace | b64enc }}
  POSTAL_URL: {{ printf "http://postal.%s.svc.cluster.local" .Values.namespace | b64enc }}
  SIGNATURE_URL: {{ printf "http://signature.%s.svc.cluster.local" .Values.namespace | b64enc }}
  STAFFNGO_URL: {{ printf "http://staffngo.%s.svc.cluster.local" .Values.namespace | b64enc }}
  SUBSCRIPTION_URL: {{ printf "http://subscription.%s.svc.cluster.local" .Values.namespace | b64enc }}
  SYNCFUSION_LISENCE: {{ .Values.common.secretValues.SYNCFUSION_LISENCE | b64enc }}
  VAULT_URL: {{ printf "http://vault.%s.svc.cluster.local" .Values.namespace | b64enc }}

metadata:
  name: common
type: Opaque
