---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dbConnections.name}}
data:
  digidoc: {{ .Values.dbConnections.values.digidoc}}
  external: {{ .Values.dbConnections.values.external}}
  identity: {{ .Values.dbConnections.values.identity}}
  laborregister: {{ .Values.dbConnections.values.laborregister}}
  monitoring: {{ .Values.dbConnections.values.monitoring}}
  notification: {{ .Values.dbConnections.values.notification}}
  postal: {{ .Values.dbConnections.Values.postal}}
  scheduler: {{ .Values.dbConnections.values.scheduler}}
  signature: {{ .Values.dbConnections.values.signature}}
  staffngo: {{ .Values.dbConnections.values.staffngo}}
  subscription: {{ .Values.dbConnections.values.subscription}}
  vault: {{ .Values.dbConnections.values.vault}}