---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-staffngo
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  parentRefs:
    - name: {{ .Values.traefik.gateway.name }}
      namespace: {{ .Values.traefik.gateway.namespace }}
      sectionName: {{ .Values.traefik.gateway.sectionName }}
  hostnames:
    - "api-{{ .Values.environment | lower }}.staffngo.com"
  rules:
    {{- range $name, $svc := .Values.services }}
    {{- if and $svc.enabled $svc.env.API_BASE_PATH }}
    - matches:
        - path:
            type: PathPrefix
            value: /{{ $svc.env.API_BASE_PATH }}
      backendRefs:
        - name: {{ $name }}
          port: {{ $svc.service.port | int }}
    {{- end }}
    {{- end }}
