{{- if .Values.services.redis.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  serviceName: redis
  replicas: {{ .Values.services.redis.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:{{ .Values.services.redis.tag }}
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: bus
          resources:
            {{- toYaml .Values.services.redis.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /usr/local/etc/redis
      volumes:
        - name: config
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.services.redis.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.services.redis.storage }}
{{- end }}