namespace: "staffngo"
environment: "Demo"

#----------------------------------------------------

registry:
  server: "staffngoacr.azurecr.io"
  secretName: "acr-pull-secret"

acrSecret:
  name: "acr-pull-secret"
  username: "staffngoacr"
  password: ""

#----------------------------------------------------

secret:
  name: "common"
  secretValues:
    API_BASE_URL: "https://api.staffngo.com"
    ASPNETCORE_HTTP_PORTS: "80"
    AZURE_SERVICEBUS_CONNECTION_STRING: ""
    AZURE_STORAGE_CONNECTION_STRING: ""
    SYNCFUSION_LISENCE: ""

configMap:
  name: "database-connections"
  values:
    digidoc: ""
    external: ""
    identity: ""
    laborregister: ""
    monitoring: ""
    notification: ""
    postal: ""
    scheduler: ""
    signature: ""
    staffngo: ""
    subscription: ""
    vault: ""

#----------------------------------------------------
redis:
  enabled: true
  tag: "8.6"
  replicaCount: 3
  clusterReplicas: 0
  storageClassName: "managed-csi"
  storage: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

services:
  digidoc:
    image: "demo-digidoc.api"
    tag: "20260324.1915"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "200m"
        memory: "1024Mi"
    env:
      API_BASE_PATH: "digidoc"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "digidoc"
    enabled: true

  external:
    image: "demo-external.api"
    tag: "20260331.1610"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "20m"
        memory: "128Mi"
      limits:
        cpu: "40m"
        memory: "256Mi"
    env:
      API_BASE_PATH: "external"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: DB_CONNECTION_STRING
        configMapKey: "external"
    enabled: true

  identity:
    image: "demo-identity.api"
    tag: "20260324.1919"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "100m"
        memory: "512Mi"
    env:
      AZURE_CLIENT_ID: ""
      AZURE_TENANT_ID: ""
      AZURE_CLIENT_SECRET: ""
      REDIS_CONNECTION_STRING: ""
      API_BASE_PATH: "identity"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "identity"
    enabled: true

  laborregister:
    image: "demo-laborregister.api"
    tag: "20260324.1905"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "10m"
        memory: "128Mi"
      limits:
        cpu: "20m"
        memory: "256Mi"
    env:
      API_BASE_PATH: "laborregister"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "laborregister"
    enabled: true

  monitoring:
    image: "demo-monitoring.api"
    tag: "20251006.2114"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "20m"
        memory: "256Mi"
      limits:
        cpu: "40m"
        memory: "512Mi"
    env:
      API_BASE_PATH: "monitoring"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "monitoring"
    enabled: true

  notification:
    image: "demo-notification.api"
    tag: "20260324.1910"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "10m"
        memory: "512Mi"
      limits:
        cpu: "20m"
        memory: "1024Mi"
    env:
      API_BASE_PATH: "notification"
      ENABLE_INSTALLERS: "true"
      NDR_CREDENTIALS: ""
      BREVO_API_KEY: ""
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "notification"
    enabled: true

  postal:
    image: "demo-postal.api"
    tag: "20260302.0955"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "10m"
        memory: "128Mi"
      limits:
        cpu: "20m"
        memory: "256Mi"
    env:
      API_BASE_PATH: "postal"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "postal"
    enabled: true

  scheduler:
    image: "demo-scheduler.api"
    tag: "20260302.0754"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "10m"
        memory: "128Mi"
      limits:
        cpu: "20m"
        memory: "256Mi"
    env:
      API_BASE_PATH: "scheduler"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "scheduler"
    enabled: true

  signature:
    image: "demo-signature.api"
    tag: "20260217.1734"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "10m"
        memory: "256Mi"
      limits:
        cpu: "20m"
        memory: "512Mi"
    env:
      API_BASE_PATH: "signature"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "signature"
    enabled: true

  staffngo:
    image: "demo-staffngo.api"
    tag: "20260331.1614"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "250m"
        memory: "2048Mi"
      limits:
        cpu: "500m"
        memory: "4096Mi"
    env:
      API_BASE_PATH: "staffngo"
      ENABLE_INSTALLERS: "true"
      OODRIVE_TOKEN: ""
      REDIS_CONNECTION_STRING: ""
      UBIQOD_API_KEY: ""
      REDIS_WS_CONNECTION_STRING: ""
      SPEECH_TO_ACTION_API_KEY: ""
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "staffngo"
    enabled: true

  subscription:
    image: "demo-subscription.api"
    tag: "20260302.0946"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "10m"
        memory: "256Mi"
      limits:
        cpu: "20m"
        memory: "512Mi"
    env:
      API_BASE_PATH: "signature"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "signature"
    enabled: true

  vault:
    image: "demo-vault.api"
    tag: "20260217.1605"
    replicaCount: 1
    pullPolicy: "IfNotPresent"
    service:
      type: "ClusterIP"
      port: 80
    resources:
      requests:
        cpu: "10m"
        memory: "256Mi"
      limits:
        cpu: "20m"
        memory: "512Mi"
    env:
      API_BASE_PATH: "signature"
      ENABLE_INSTALLERS: "true"
    configKeys:
      - envVar: "DB_CONNECTION_STRING"
        configMapKey: "signature"
    enabled: true
