apiVersion: v2
name: redis
description: Helm chart to deploy Redis standalone or cluster
type: application
version: 0.1.3
appVersion: "8.6"
icon: https://cdn.iconscout.com/icon/free/png-256/free-redis-logo-icon-svg-download-png-3030242.png?f=webp&w=256
